version: "3.8"

services:
  erudyt_api_db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_API_DATABASE}
    ports:
      - ${MYSQLDB_API_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
